# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZg7SPQJLkeTsXAtF5SdOmwR6MGypt77
"""

import streamlit as st
import pandas as pd
import pickle
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef,
    confusion_matrix, classification_report
)
import os

# --- APP CONFIGURATION ---
st.set_page_config(page_title="Diabetes Risk Dashboard", layout="wide")

# Unique styling for BITS Assignment
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; border: 1px solid #e0e0e0; }
    </style>
    """, unsafe_allow_html=True)

# --- HEADER SECTION ---
st.title("🏥 Clinical Diagnostic Assistant")
st.write("Early Stage Diabetes Risk Assessment - ML Performance Review")

# --- DATA INGESTION ---
with st.sidebar:
    st.header("📂 Data Management")
    uploaded_file = st.file_uploader("Import Raw CSV for Testing", type="csv") # Requirement 5a [cite: 91]

    if os.path.exists("test_sample.csv"):
        with open("test_sample.csv", "rb") as f:
            st.download_button("📥 Get Template CSV", f, "template.csv", "text/csv")

    st.divider()
    st.header("⚙️ Model Configuration")
    # Requirement 5b [cite: 92]
    choice = st.selectbox("Predictive Engine",
                          ["Random Forest", "XGBoost", "Decision Tree", "kNN", "Logistic Regression", "Naive Bayes"])

# --- PROCESSING ENGINE ---
if uploaded_file:
    raw_df = pd.read_csv(uploaded_file)

    # Dashboard Layout
    tab1, tab2 = st.tabs(["📋 Data Preview", "📈 Model Analysis"])

    with tab1:
        st.dataframe(raw_df.style.highlight_max(axis=0), use_container_width=True)

    with tab2:
        try:
            # Load Resources
            with open('model/encoders.pkl', 'rb') as f:
                encoders = pickle.load(f)
            with open('model/scaler.pkl', 'rb') as f:
                scaler = pickle.load(f)

            # Map choice to filename
            fname = f"model/{choice.lower().replace(' ', '_')}.pkl"
            with open(fname, 'rb') as f:
                model = pickle.load(f)

            # --- CUSTOM PREPROCESSING ---
            # Fix case sensitivity by forcing lowercase
            work_df = raw_df.copy()
            work_df.columns = [c.lower() for c in work_df.columns]

            # Encoding features
            for col, le in encoders.items():
                if col != 'target' and col in work_df.columns:
                    work_df[col] = le.transform(work_df[col])

            # Scaling numericals
            if 'age' in work_df.columns:
                work_df['age'] = scaler.transform(work_df[['age']])

            # Label Extraction
            target_key = 'class' if 'class' in work_df.columns else 'target'
            X = work_df.drop(target_key, axis=1)
            y_actual = encoders['target'].transform(raw_df[target_key])

            # Inference
            predictions = model.predict(X)
            probabilities = model.predict_proba(X)[:, 1] if hasattr(model, "predict_proba") else predictions

            # --- METRICS DISPLAY (Requirement 5c) --- [cite: 93, 40-46]
            st.subheader(f"System Evaluation: {choice}")

            m_cols = st.columns(3)
            m_cols[0].metric("Accuracy", f"{accuracy_score(y_actual, predictions):.4f}")
            m_cols[1].metric("AUC-ROC", f"{roc_auc_score(y_actual, probabilities):.4f}")
            m_cols[2].metric("MCC Score", f"{matthews_corrcoef(y_actual, predictions):.4f}")

            m_cols_2 = st.columns(3)
            m_cols_2[0].metric("Precision", f"{precision_score(y_actual, predictions):.4f}")
            m_cols_2[1].metric("Recall", f"{recall_score(y_actual, predictions):.4f}")
            m_cols_2[2].metric("F1 Score", f"{f1_score(y_actual, predictions):.4f}")

            # --- VISUALS (Requirement 5d) --- [cite: 94]
            st.divider()
            v_col1, v_col2 = st.columns([1, 1.5])

            with v_col1:
                st.markdown("**Error Distribution (Confusion Matrix)**")
                fig, ax = plt.subplots()
                sns.heatmap(confusion_matrix(y_actual, predictions), annot=True, fmt='d', cmap='YlGnBu')
                st.pyplot(fig)

            with v_col2:
                st.markdown("**Detailed Classification Report**")
                st.text(classification_report(y_actual, predictions))

        except Exception as err:
            st.error(f"Inference Error: {err}")
else:
    st.info("System Ready. Please upload a test dataset from the sidebar to begin analysis.")