# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZg7SPQJLkeTsXAtF5SdOmwR6MGypt77
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import pickle
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

st.set_page_config(page_title="Diabetes Risk Predictor", layout="wide")

def load_artifact(path):
    with open(path, 'rb') as f:
        return pickle.load(f)

st.title("🩺 Diabetes Risk Prediction (Raw Data Inference)")

# Load preprocessing artifacts
try:
    encoders = load_artifact('model/encoders.pkl')
    scaler = load_artifact('model/scaler.pkl')
except:
    st.error("Model artifacts not found. Please run train_models.py first.")
    st.stop()

# Sidebar
model_option = st.sidebar.selectbox("Select ML Model",
    ("Logistic Regression", "Decision Tree", "kNN", "Naive Bayes", "Random Forest", "XGBoost"))
uploaded_file = st.sidebar.file_uploader("Upload Raw CSV Data", type=["csv"])

if uploaded_file:
    raw_df = pd.read_csv(uploaded_file)
    st.subheader("Raw Data Preview")
    st.write(raw_df.head())

    # --- INTERNAL PREPROCESSING ---
    processed_df = raw_df.copy()

    # 1. Encode features using saved encoders
    for col, le in encoders.items():
        if col != 'target' and col in processed_df.columns:
            processed_df[col] = le.transform(processed_df[col])

    # 2. Scale Age
    processed_df['age'] = scaler.transform(processed_df[['age']])

    # 3. Separate features and target
    X_eval = processed_df.iloc[:, :-1]
    y_true_raw = raw_df.iloc[:, -1]
    y_true = encoders['target'].transform(y_true_raw)

    # --- PREDICTION ---
    model_path = f"model/{model_option.replace(' ', '_').lower()}.pkl"
    model = load_artifact(model_path)
    y_pred = model.predict(X_eval)

    # Results Display
    col1, col2 = st.columns(2)
    with col1:
        st.metric("Model Accuracy", f"{accuracy_score(y_true, y_pred):.2%}")
        st.text("Classification Report:")
        st.text(classification_report(y_true, y_pred))

    with col2:
        cm = confusion_matrix(y_true, y_pred)
        fig, ax = plt.subplots()
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
        st.pyplot(fig)