# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZg7SPQJLkeTsXAtF5SdOmwR6MGypt77
"""

import streamlit as st
import pandas as pd
import pickle
import numpy as np
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef
)
import seaborn as sns
import matplotlib.pyplot as plt
import os

# --- PAGE CONFIG ---
st.set_page_config(page_title="Diabetes Risk Performance Review", layout="wide")
st.title("🩺 ML Classification Performance - Early Stage Diabetes Risk")

# --- SIDEBAR: DATA UPLOAD --- [Step 5a requirement]
st.sidebar.header("Step 1: Upload Test Data")
uploaded_file = st.sidebar.file_uploader("Upload your raw test CSV", type="csv")

# --- SIDEBAR: DOWNLOAD SAMPLE ---
if os.path.exists("test_sample.csv"):
    with open("test_sample.csv", "rb") as file:
        st.sidebar.download_button(
            label="Download Template CSV",
            data=file,
            file_name="test_sample.csv",
            mime="text/csv"
        )

if uploaded_file:
    # 1. Load Data
    raw_data = pd.read_csv(uploaded_file)
    st.write("### Raw Test Data Preview")
    st.dataframe(raw_data.head())

    # 2. Model Selection [Step 5b requirement]
    st.sidebar.header("Step 2: Model Selection")
    model_option = st.sidebar.selectbox(
        'Which model would you like to evaluate?',
        ('Logistic Regression', 'Decision Tree', 'kNN', 'Naive Bayes', 'Random Forest', 'XGBoost')
    )

    try:
        # Load Artifacts
        encoders = pickle.load(open('model/encoders.pkl', 'rb'))
        scaler = pickle.load(open('model/scaler.pkl', 'rb'))

        model_map = {
            'Logistic Regression': 'logistic_regression.pkl',
            'Decision Tree': 'decision_tree.pkl',
            'kNN': 'knn.pkl',
            'Naive Bayes': 'naive_bayes.pkl',
            'Random Forest': 'random_forest.pkl',
            'XGBoost': 'xgboost.pkl'
        }

        model = pickle.load(open(os.path.join('model', model_map[model_option]), 'rb'))

        # --- PREPROCESSING (FIXING CASE SENSITIVITY) ---
        processed_df = raw_data.copy()
        # Force all columns to lowercase to match training
        processed_df.columns = [c.lower() for c in processed_df.columns]

        # Apply Label Encoding
        for col, le in encoders.items():
            if col != 'target' and col in processed_df.columns:
                processed_df[col] = le.transform(processed_df[col])

        # Apply Scaling to age (ensure col name is lowercase 'age')
        if 'age' in processed_df.columns:
            processed_df['age'] = scaler.transform(processed_df[['age']])

        # Identify Target
        target_col = 'class' if 'class' in processed_df.columns else 'target'
        X_test = processed_df.drop(target_col, axis=1)
        y_test = encoders['target'].transform(raw_data[target_col])

        # 3. Predictions
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else y_pred

        # --- DISPLAY METRICS [Step 5c requirement] ---
        st.divider()
        st.subheader(f"📈 Performance Metrics: {model_option}")

        col1, col2, col3 = st.columns(3)
        col1.metric("Accuracy", f"{accuracy_score(y_test, y_pred):.4f}")
        col2.metric("AUC Score", f"{roc_auc_score(y_test, y_prob):.4f}")
        col3.metric("Precision", f"{precision_score(y_test, y_pred):.4f}")

        col4, col5, col6 = st.columns(3)
        col4.metric("Recall", f"{recall_score(y_test, y_pred):.4f}")
        col5.metric("F1 Score", f"{f1_score(y_test, y_pred):.4f}")
        col6.metric("MCC Score", f"{matthews_corrcoef(y_test, y_pred):.4f}")

        # --- VISUALS [Step 5d requirement] ---
        st.divider()
        viz1, viz2 = st.columns(2)
        with viz1:
            st.markdown("**Classification Report**")
            st.text(classification_report(y_test, y_pred))
        with viz2:
            st.markdown("**Confusion Matrix**")
            fig, ax = plt.subplots(figsize=(5, 4))
            sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
            st.pyplot(fig)

    except Exception as e:
        st.error(f"Error: {e}")
else:
    st.info("Please upload a test CSV to begin.")